---
title: "Crossings with controlled DL sequence"
output: html_notebook
---


```{r}
setwd("~/projects/gapbaseline")
rm(list=ls())

library(plotrix)
library(tidyverse)
library(forcats)
library(stringr)
library(broom)
library(lmerTest)
library(lmtest)


BAD_LANGS = c("akk", "aii", "am", "ga", "yue", "krl", "kpv", "lt", "mr", "orv", "sa", "swl", "tl", "wbp", "yo", "gun", "la", "gl") # gl has no data

NAMES = c("lang","dtype","sent_id","length","max_arity","avg_arity","projD","gapD","illnestedness","edgex","dir","dd", "proj","edgeD","endPoint","HDD")

t = read_csv("typology3.csv")
dt = read_tsv("Random_trees_DL_sequence_unbounded_baseline.csv", col_names=F)
do = read_tsv("Random_order_DL_sequence_unbounded_baseline.csv", col_names=F)
names(dt) = NAMES
names(do) = NAMES

d = do %>%
  filter(dtype == "random") %>%
  mutate(dtype="rla") %>%
  bind_rows(dt) %>%
  mutate(lang=str_replace(lang, "\\\\", ""),
         lang=str_replace(lang, "/", ""),
         lang=str_replace(lang, "-1", "")) %>%
  filter(!(lang %in% BAD_LANGS)) 

d_summary = d %>% 
  filter(!is.na(dtype)) %>%
  group_by(lang, dtype, sent_id, length, max_arity, projD) %>%
    summarise(num_cross=sum(1-proj),
              dl=sum(dd+1),
              num_hf=sum(dir == "RL")) %>%
    ungroup() %>%
  mutate(is_real=if_else(dtype == "real", 1, 0))

R_LANGS = unique(d_summary$lang)

d_summary %>%
  group_by(lang, dtype, length) %>%
    summarise(mean_num_cross=mean(num_cross),
              mean_head_final=mean(num_hf/length)) %>%
    ungroup() %>%
  mutate(dtype=if_else(dtype == "random", "random trees", if_else(dtype == "rla", "random linear arrangements", "real trees"))) %>%
  ggplot(aes(x=length, y=mean_num_cross, color=lang, label=lang)) +
    geom_text() +
    geom_line() + 
    facet_grid(lang~dtype) + 
    theme_bw() +
    scale_color_discrete(guide=FALSE) +
    xlim(2,NA) +
    xlab("Sentence length") +
    ylab("Mean number of crossing arcs per sentence")



```

```{r}
# Crossing rate stats

mp0 = d_summary %>%
  glm(num_cross ~ I(log(length)), data=., family="poisson")

mp = d_summary %>%
  mutate(is_real=if_else(dtype == "real", 1, 0)) %>%
  glm(num_cross ~ I(log(length)) + I(log(length)):is_real, data=., family="poisson")

mpi = d_summary %>%
  glm(num_cross ~ I(log(length)) + I(log(length))*dtype, data=., family="poisson")

mg = d_summary %>%
  glm(num_cross ~ 0 + length + length*dtype, data=.)

mg2 = d_summary %>%
  glm(num_cross ~ 0 + I(length^2) + I(length^2) * dtype, data=.)
  

```


```{r}
# Plot regression fits

d_summary %>% 
    mutate(poisson_regression=exp(predict(mpi))) %>%
    group_by(lang, dtype, length) %>%
      summarise(mean_num_cross=mean(num_cross), 
                mean_predicted_poisson=mean(poisson_regression)) %>%
      ungroup() %>%
    mutate(dtype=if_else(dtype == "random", "DL-controlled random trees", if_else(dtype == "rla", "DL-controlled RLAs", "real trees"))) %>%
    mutate(dtype=factor(dtype, levels=c("DL-controlled random trees", "DL-controlled RLAs", "real trees"))) %>%
    ggplot(aes(x=length, y=mean_num_cross, color=lang, label=lang)) +
      geom_text() +
      geom_line() + 
      facet_wrap(~dtype) + 
      theme_bw() +
      scale_color_discrete(guide=FALSE) +
      xlim(2,NA) +
      xlab("Sentence length") +
      ylab("Mean number of crossing arcs per sentence") + 
      geom_line(aes(y=mean_predicted_poisson), color="black", size=2, linetype="dashed")

ggsave("crossings_random_real.pdf", width=7, height=3.5)


```
```{r}

d2 = d_summary %>% 
    group_by(lang, dtype, length) %>%
      summarise(n=n(),
                m=mean(num_cross),
                se=std.error(num_cross),
                upper=m+1.96*se,
                lower=m-1.96*se) %>%
      ungroup() 


EPSILON = .00001

d2log = d2 %>%
  filter(length>2) %>%
  mutate(m=m+EPSILON,
         m=log(m),
         upper=log(pmax(EPSILON, upper)),
         lower=log(pmax(EPSILON, lower)),
         length=log(length))

d2 %>%
    group_by(lang, dtype) %>%
      mutate(n=sum(n)) %>%
      ungroup() %>%
    group_by(lang) %>%
      mutate(n=min(n)) %>%
      ungroup() %>%
    mutate(dtype=if_else(dtype == "random", "DL-controlled random trees", if_else(dtype == "rla", "DL-controlled RLAs", "real trees"))) %>%
    mutate(dtype=factor(dtype, levels=c("DL-controlled random trees", "DL-controlled RLAs", "real trees"))) %>%
    inner_join(t) %>%
    mutate(lang_name=str_c(lang_name, ", ", "N=", n)) %>%
    mutate(lang_name=fct_reorder(lang_name, -n)) %>%
    filter(lang != "gl") %>%
    ggplot(aes(x=length, y=m, color=dtype, ymin=lower, ymax=upper)) +
      geom_line() +
      geom_errorbar() +
      facet_wrap(~lang_name, ncol=5, scale="free_y") +
      #xlim(2, NA) +
      theme_bw() +
      theme(legend.title=element_blank(),
            legend.position=c(.75, .03),
            legend.text=element_text(size=12)) +
      xlab("Sentence length") +
      ylab("Mean number of crossing arcs per sentence")

ggsave("crossings_real_random_by_lang.pdf", width=9, height=13)

```



```{r}
# By-language regressions
langs = d_summary %>% select(lang) %>% distinct() %>% pull(lang)

dtype_regression_test = function(d, include) {
  m0 = glm(num_cross ~ I(log(length)), data=filter(d, dtype %in% c("real", include)), family="poisson")
  m = glm(num_cross ~ I(log(length)) + I(log(length))*dtype, data=filter(d, dtype %in% c("real", include)), family="poisson")
  #print(summary(m))
  #print(lrtest(m0, m))
  lrtest(m0, m) %>% tidy() %>% filter(!is.na(p.value)) %>% pull(p.value)
}

for (l in langs) {
  dl = filter(d_summary, lang == l)
  print(l)
  print(dtype_regression_test(dl, "random"))
  print(dtype_regression_test(dl, "rla"))
}

```

```{r}


dr = read_tsv("all_measures_real_SUD_all.csv", col_names=F)
names(dr) = NAMES
dr = dr %>%
  mutate(lang=str_replace(lang, "\\\\", ""),
         lang=str_replace(lang, "/", ""),
         lang=str_replace(lang, "-1", "")) %>%
  filter(!(lang %in% BAD_LANGS))


MAXLEN = 30

dr_summary = dr %>%
  filter(!is.na(dtype),
         length<=MAXLEN) %>%
  group_by(lang, dtype, sent_id, length, max_arity, projD) %>%
    summarise(num_cross=sum(1-proj),
              dl=sum(dd+1)) %>%
    ungroup() %>%
  bind_rows(filter(d_summary, dtype == "random"),
            filter(d_summary, dtype == "rla")) %>%
  select(lang, dtype, length, num_cross)

langs = dr_summary %>% select(lang) %>% distinct() %>% pull

for (lang in langs) {
  dr_summary = dr_summary %>%
    bind_rows(data.frame(lang=lang,
                         length=12:MAXLEN,
                         dtype="random")) %>%
    bind_rows(data.frame(lang=lang,
                         length=12:MAXLEN,
                         dtype="rla"))
}
  
  

# See how well the regression fit to short sentences fits the long sentences...
dr_summary %>% 
  mutate(predicted=predict(mg, dr_summary)) %>%
  group_by(lang, dtype, length) %>%
    summarise(mean_num_cross=mean(num_cross), 
              mean_predicted=mean(predicted)) %>%
    ungroup() %>%
  mutate(dtype=if_else(dtype == "random", "DL-controlled random trees", if_else(dtype == "rla", "DL-controlled RLAs", "real trees"))) %>%
  mutate(dtype=factor(dtype, levels=c("DL-controlled random trees", "DL-controlled RLAs", "real trees"))) %>%
  ggplot(aes(x=length, y=mean_num_cross, color=lang, label=lang)) +
      geom_text() +
      geom_line() + 
      facet_wrap(~dtype) + 
      theme_bw() +
      scale_color_discrete(guide=FALSE) +
      xlim(2,NA) +
      xlab("Sentence length") +
      ylab("Mean number of crossing arcs per sentence") + 
      geom_line(aes(y=mean_predicted), color="black", size=1, linetype="dashed")

```

```{r}
# Generate figure 
to_plot = dr_summary %>%
  mutate(predicted=exp(predict(mpi, dr_summary))) %>%
  group_by(lang, dtype, length) %>%
    summarise(mean_num_cross=mean(num_cross), 
              mean_predicted=mean(predicted)) %>%
    ungroup() %>%
  mutate(dtype=if_else(dtype == "random", "DL-controlled random trees", if_else(dtype == "rla", "DL-controlled RLAs", "real trees"))) %>%
  mutate(dtype=factor(dtype, levels=c("DL-controlled random trees", "DL-controlled RLAs", "real trees")))

to_plot %>%
  filter(dtype == "real trees") %>%
  ggplot(aes(x=length, y=mean_num_cross, color=lang, label=lang)) +
      geom_text() +
      geom_line() + 
      theme_bw() +
      scale_color_discrete(guide=FALSE) +
      xlim(2,NA) +
      xlab("Sentence length") +
      ylab("Mean number of crossing arcs per sentence") +
      geom_line(data=filter(to_plot, length<12), aes(y=mean_predicted, linetype=dtype), color="black", size=1) +
      geom_vline(xintercept=11, color="red") +
      labs(linetype="Regression fit")

ggsave("~/projects/gapbaseline/regression_fit_long_sentences.pdf", width=9, height=5)

```


```{r}
# Define a permutation test

permutation_difference = function(f, xs, N) {
  M = length(xs)
  xs = sample(xs)
  one = xs[1:N]
  two = xs[(N+1):M]
  f(one) - f(two)
}

permutation_test = function(f, xs, ys, num_samples) {
  # Is f(x) significantly different from f(y)?
  N = length(xs)
  true_difference = f(xs) - f(ys)
  together = c(xs, ys)
  baseline_differences = replicate(num_samples, permutation_difference(f, together, N))
  d = data.frame(difference=baseline_differences) %>%
    mutate(type="baseline") %>%
    bind_rows(data.frame(difference=true_difference) %>% mutate(type="real")) %>%
    arrange(difference) %>%
    mutate(index=1:(num_samples+1))
  i = filter(d, type == "real") %>% pull(index)
  # If there's a tie, we want to always assign the real thing the less extremal rank
  # So we make sure the real value is on top of most of the baseline values, not below them,
  # and then resort so that the lexicographic sorting (baseline < real) will take care of the rest
  if (i > num_samples/2) {
    i = d %>% 
      select(-index) %>% 
      arrange(-difference) %>% 
      mutate(index=1:(num_samples+1)) %>% 
      filter(type == "real") %>% 
      pull(index)
  }
  i / (num_samples+1)
}

```

```{r}
# Apply permutation test to crossing data
pt = d_summary %>% 
  select(lang, dtype, length, dl, num_cross, sent_id) %>% 
  spread(dtype, num_cross) %>% 
  group_by(lang, length) %>% 
    summarise(n=n(), m_rand = mean(random, na.rm=T), m_real = mean(real, na.rm=T), diff=m_rand - m_real, p=permutation_test(mean, real, random, 1000)) %>%
    ungroup()

```

```{r}
# Plot real vs. baseline differences with permutation test significance

alpha = .05

pt %>% 
  mutate(significance=if_else(p<alpha, "p<.05", "n.s.")) %>%
  ggplot(aes(x=length, y=diff, label=lang, color=significance)) +
    geom_text() +
    xlim(3, NA) +
    xlab("Sentence length") +
    ylab("Difference in mean number of crossing arcs, random - real") +
    theme_bw()
    
  
  


```


```{r}

dc_ud = read_csv("crossings_survey_ud.csv") %>% mutate(corpus="ud")
dc_sud = read_csv("crossings_survey_sud.csv") %>% mutate(corpus="sud")
dc = bind_rows(dc_ud, dc_sud)

dc_summary = dc %>% 
  group_by(corpus, lang, start_line, n) %>% 
    summarise(num_cross=sum(crossing)) %>% 
    ungroup() %>% 
  group_by(corpus, lang) %>%
    mutate(num_sentences=n()) %>%
    ungroup() %>%
  group_by(corpus, lang, n, num_sentences) %>% 
    summarise(m=mean(num_cross)) %>% 
    ungroup() 

dc_summary %>% 
  filter(!(lang %in% BAD_LANGS)) %>%
  filter(n<20) %>% 
  filter(num_sentences>5000) %>%
  ggplot(aes(x=n, y=m, color=lang, label=lang)) + stat_smooth() + geom_text() + facet_wrap(~corpus) + scale_color_discrete(guide=FALSE) + ylab("Mean number of nonprojective arcs per sentence") + xlab("Sentence length")

ggsave("crossings_ud_sud.pdf")

```


```{r}

combined = dc_summary %>% 
  rename(dtype=corpus, length=n, mean_num_cross=m) %>% 
  select(-num_sentences) %>% 
  bind_rows(d_summary)

combined %>% 
  filter(length < 12, !(lang %in% BAD_LANGS), dtype %in% c("random", "sud"), lang %in% R_LANGS) %>% 
  ggplot(aes(x=length, y=mean_num_cross, color=lang, label=lang)) + geom_text() + stat_smooth() + facet_wrap(~dtype)


```